# Copyright (c) 2012-2016 Sebastien Rombauts (sebastien.rombauts@gmail.com)



sudo: false



language: generic

cache:
  apt: true

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
    - env: CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
          sources: *sources
    - env: CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          packages:
            - clang-3.6
sources: *sources




addons:
  apt:
    packages:
    - cppcheck
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install -qq g++-4.9
    - sudo apt-get install -qq g++-5

before_install:
  - pip install --user cpp-coveralls

# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DSQLITECPP_USE_GCOV=ON -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_BUILD_TESTS=ON ..

# build examples, and run tests (ie make & make test)
script:
  - cmake --build .
  - ctest --output-on-failure

# publish GCov coveralls results
after_success:
  - coveralls -e build/CMakeFiles -e examples -e googletest -e sqlite3 -e tests
